#' Read an LD file generated by PLINK2
#'
#' @param ldFile filename ("Genotype_<chromosome>_<start>_<end>.ld")
#' @return ldData DataFrame (CHR_A, BP_A, SNP_A, CHR_B, BP_B, SNP_B, R2)
#' @export
ldRead <- function (ldFile) {
    ldData <- read.table(ldFile, header = TRUE)
    return (ldData)
}

#' Takes a PLINK file containing pairwise R2 values between all pairs of SNPs
#' and converts this into an N(snp) x N(snp) dissimilarity matrix.
#' The dissimilarity matrix may then be used as per any other dissimilarity
#' matrix, e.g. clustering.
#'
#' @param ldData data frame. Default LD output form PLINK2. Use ldRead().
#' @return ldData matrix. Dissimilarity matrixs, measured in R2.
#' @export
ldDissimilarity <- function (ldData) {

    # unique list of SNPs, ordered in chromosomal order
    # (this order is the default ordering form PLINK, and not explicit).
    # To be used to order the columns of hte dissimilarity matrix
    snpOrder <- unique(ldData$SNP_B)

    # wrangle the data into a dissimilarity matrix
    ldData <- reshape2::dcast(ldData[, c("SNP_A", "SNP_B", "R2")],
                              SNP_A ~ SNP_B,
                              value.var = "R2")

    rownames(ldData) <- ldData[, 1]     # set rownames = SNP names
    ldData <- as.matrix(ldData[, -1])   # drop the first column (now rownames)
    ldData[is.na(ldData)] <- 0          # set missing LD values as minimum LD
    ldData <- 1 - ldData                # create dissimilarity measure
    ldData <- ldData[, snpOrder]        # reorder columns in chromosomal order

    return (ldData)
}

#' Reads in the LD data (PLINK output) and returns an ordered summary.
#'
#' @param ldProxyData matrix. Use ldProxy() and ldRead() to generate.
#' @return proxyData data frame. (Chr, Pos(A), Pos(B), SNP(A), SNP(B), R2). Ordered by R2 decreasing.
#' @export
ldProxyTable <- function (ldProxyData) {

    # wrangle
    columns <- c("CHR_A", "BP_A", "BP_B", "SNP_A", "SNP_B", "R2")
    ldProxyData <- ldProxyData[, columns]
    colnames(ldProxyData) <- c("Chr", "Pos(A)", "Pos(B)", "SNP(A)", "SNP(B)", "R2")

    return (ldProxyData[order(ldProxyData$R2, decreasing = TRUE), ])
}
